# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "itu-academic-document"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Frederik Bertelsen <@FrederikBertelsen>"]
license = "MIT"
description = "Academic document at IT University of Copenhagen (ITU)."
repository = "https://github.com/FrederikBertelsen/typst-itu-template"
keywords = [
  "ITU",
  "IT University of Copenhagen",
  "university",
  "computer science",
  "software development",
  "datalogi",
  "academic",
  "thesis",
  "report",
  "paper",
]
categories = ["report", "thesis", "paper"]
disciplines = ["computer-science"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# Template package configuration. If this repository is a template,
# the `path` should point to the directory containing the files that
# will be copied into a new project. The `entrypoint` is relative to
# that path. Provide a PNG or lossless WebP thumbnail at `thumbnail`.
[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
